fix: Compatibility with multirow-tab
black7375/Firefox-UI-Fix pull request #797
Opened 2023-10-16 16:04 UTC by surapunoyousei

Floorp Injection. The old code causes breaking Floorp's multirow-tabs (Paxmod)

**Describe the PR**

**PR Type**

- [ ] `Add:` Add feature or enhanced.
- [x] `Fix:` Bug fix or change default values.
- [ ] `Clean:` Refactoring.
- [ ] `Doc:` Update docs.

**Related Issue**

#777

**Screenshots**

https://github.com/black7375/Firefox-UI-Fix/assets/73892113/2c14bad3-76b7-49f8-a88b-78ba5080e685

**Additional context**

The issue should not be closed immediately after the merge, as there may be other code causing this problem. I will carry on research this issue.

2023-10-16 19:43 UTC, black7375 requested changes
Thank you for contributing. I was busy and I couldn't test it. I'll try it soon.

2023-10-16 19:43 UTC, black7375 commented on css/leptonChromeESR.css
> +  /*= Lightmode - Color darker ===============================================  :ro  :root[lwtheme-mozlightdark]:not([lwthemetextcolor="bright"]),
The sass file seems to have not compiled properly.

2023-10-16 19:43 UTC, black7375 commented on css/leptonChromeESR.css
> +  @supports -moz-bool-pref("userChrome.icon.menu") {
And here.

2023-10-16 19:43 UTC, black7375 commented on src/padding/_tabbar_width.scss
> +         & :not([multibar]) {
IMO, I think this code will be better to exclude `multibar`.

```scss
  #TabsToolbar:not([multibar]) .tabbrowser-tab {
      // Original: padding-inline 2px, margin-inline 0px #643
      &[pinned] {
        padding-inline: 1px !important;
      }
      &:not([pinned]) {
        &:not(:first-of-type) {
          margin-inline: -1px !important;
        }
        &:first-of-type {
          margin-inline-end: -1px !important;
        }
      }
    }
  }
```

2023-10-16 22:22 UTC, surapunoyousei commented
Oops, Something went wrong when the building.

I changed some code that not relating to the problem. Fix it.

2023-10-17 00:04 UTC, black7375 approved these changes
The selector nature does not have a big impact on the general users.

2023-10-17 00:04 UTC, merged